### ISSUE TITLE
How to use search_read or is there a way to filter the search ?

### ISSUE THREAD

**Issue by kalmenchia** [BMKeros/odoo-webkit#27]
Hi , as per the subject , i am trying to use this it but as there are no documentation for how to use filter to search record , can anyone advice , thanks.

**Comment by hostelix** [comment]
Hello @kalmenchia! 
You can do it this way..
Example: 
```javascript
const ResUsers = new Model('res.users');

ResUsers.filter(['name', 'ilike', 'kalmenchia']).get().then(response =>  console.log(response));
```

Sorry for the lack of documentation, we are working on that..

**Comment by kalmenchia** [comment]
no problem , thanks , can we have multiple ...
ResUsers.filter(['name', 'ilike', 'kalmenchia'],['country', 'ilike', 'Malaysia'],['|']).get().then(response =>  console.log(response)); ?

**Comment by hostelix** [comment]
@kalmenchia for the moment you can only make AND filters
example:
```javascript
ResUsers
.filter(['name', 'ilike', 'kalmenchia'])
.filter(['country', 'ilike', 'Malaysia']).get().then(response =>  console.log(response));
```
['name', 'ilike', 'kalmenchia'] AND ['country', 'ilike', 'Malaysia']
the functionality to process polish notation is not yet complete

**Comment by kalmenchia** [comment]
ok, noted ,thanks for the time taken to advice.
